Numpy的基础学习

In [27]:
#导入numpy并且命名为np
import numpy as np

In [28]:
#创建三维数组，切记每个单独列表的长度要一致
arr2 = np.array([[1,2,3],[4,5,6],[7,8,0]])
print(arr2)
#打印数组的形状
print(arr2.shape)
#打印arr2数据类型
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 0]]
(3, 3)
<class 'numpy.ndarray'>


In [30]:
arr = np.array([1,2,3,4,5.0])
#属于广播操作arr中的每个元素与3比较, 并且返回一个ndarray
result = arr == 3
print(result, type(result))

[False False  True False False] <class 'numpy.ndarray'>


In [36]:
arr = np.arange(15).reshape(5,3)
print(arr)
print(arr.sum(axis=0))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[30 35 40]


In [43]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
np.random.random((2,3))


array([[0.1921137 , 0.84189918, 0.49431196],
       [0.50346489, 0.67709927, 0.95861988]])

In [94]:
from numpy import pi
np.linspace(0,2*pi,100,True)
#print(help(np.linspace))
#0.06346652*2 0.12693304

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [84]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
print(a)
print('---------')
print(b)
print('---------')
print(a*b)
print('---------')
print(a.dot(b))

[[1 1]
 [0 1]]
---------
[[2 0]
 [3 4]]
---------
[[2 0]
 [0 4]]
---------
[[5 4]
 [3 4]]


In [93]:
np.random.random((3,5))

array([[0.7177785 , 0.86031946, 0.45476446, 0.19145193, 0.12696988],
       [0.53036666, 0.64385639, 0.12040026, 0.18447079, 0.15052292],
       [0.76433349, 0.01318079, 0.2065805 , 0.43048635, 0.80145592]])